version: '3'
services:
  ssoauth:
    build: .
    container_name: ssoauth
    volumes:
      - .:/home/app
    external_links:
      - actionmedia
    ports:
      - 9080
    environment:
      - BRANCH=dev
      - VIRTUAL_HOST=ssoauth-local.surge.systems
    networks:
      - proxy
      - database
    depends_on:
      - redis

  redis:
    image: redis:latest

networks:
  database:
    external: true
  proxy:
    external: true
  default:
    external:
      name: actionmedia-network